[package]
name = "lc3vm"
version = "0.1.0"
authors = ["user <iamaero7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.3", features = ["yaml"]}
device_query = "0.2.7"
